language: node_js
node_js: lts/*

before_install:
  - npm i npm -g

install:
  - npm ci

script:
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      branch: master
